language: groovy
jvm:
  - openjdk8
branches:
  only:
    - develop
    - master
install: mvn -DskipTests=true -Dmaven.javadoc.skip=true -B -V install
script: mvn -Dmaven.javadoc.skip=true -B -V clean test
